### ISSUE TITLE
Waterkotte settings

### ISSUE THREAD

**Issue by plu** [mfechner/heizung#6]
Hi Matthias,

thank you for publishing your code and instructions here on GitHub!

I'm a bit stuck and ran out of ideas what else to try or how to narrow down the problem. So far I have successfully compiled your code and I can execute it, but as you can see it's not returning any data:

```
./readModbus -f4 -a209 -s13 -t2 -d /dev/ttyUSB0
Read register failed Connection timed out
```

In the README you mentioned:

> Maybe you have to enable the modbus protocol on your heating (mine had it enabled by default).

I've enabled the Expert Mode and entered the PIN so I can see all menu levels on the controller. I can see that line modbus is enabled, not the modem variant. Is there anything else I need to change or enable?

**Comment by mfechner** [comment]
Dear Johannes,

I have only tested it with the `Moxa NPort 5110A` and with this piece of hardware it worked fine.
As you have another device name I expect to use a USB dongle to get to RS232?

As I do not have access to the heating anymore I cannot really help you here.
But maybe the USB-RS232 dongle you have does not work with the Waterkotte heating?

Is there a reason why you not want to use the `Moxa NPort 5110A`?

**Comment by plu** [comment]
Hey Mattias,

thank you for your response!

> As you have another device name I expect to use a USB dongle to get to RS232?

Yes, that's correct. I have already tried two different USB -> RS232 adapters. I have also tried wiring up RX, TX and GND directly to the Raspberry PI, all without luck.

> Is there a reason why you not want to use the `Moxa NPort 5110A`?

It's a bit expensive, that's all :).

The other day I was measuring the voltage levels directly on the port on the Waterkotte, there was nothing showing up there, at all. Now I have the feeling that the port is just dead and it's not connected to the circuit board inside. Once it's not cold outside anymore, I'll shut the heating down and open it to verify the RS232 connector is actually connected.

Feel free to close this issue anytime you want. And thank you for your help, and for providing all this information and source code here on GitHub.

**Comment by mfechner** [comment]
There is a windows tool from Waterkotte available with it you can connect to the heating.
If you have a windows laptop it is maybe a try to test that the interface is ok.

If I remeber correctly the rs232 interface on the heating is a normal serial port so with +-12V.
If you connect that directly to a raspberry which can only handle 5V TTL this will maybe destroy the raspberry or at least the IO port. If you want to connect the raspberry you need a max232 or a similar IC to convert to good electronic voltage levels.

Good luck!
I happy to get some feedback if you have it running.

**Comment by draecke** [comment]
I have successfully used a Raspberry Pi to control the Waterkotte Heatpump! I configured the Raspbery Pi to forward the serial port via IP. The heat pump is located at a holiday home about 3 hours drive away. In my home I had a Windows laptop with the Windows software connecting to the serial port via IP. I have 2 routers that are connected via VPN, so it works as it is on the local network.
I took it apart and was trying to setup the Raspberry Pi with this software, but I didn't have enough time to do so. How even I did get the heat pump talking to the software on the Raspberry Pi, but didn't have time to get the web site on the Raspberry Pi working. After install the web site wasn't working.
I did buy 1 of those serial port level converters mfechner is mentioning i his reply, you need that for the Raspberry Pi!
If you get the software working on the Raspberry Pi I would be still interested to get it. I will get back to it in 2 or 3 months hopefully.
Good luck.

**Comment by plu** [comment]
Here the promised feedback: Now that weather is better and we don't need the heating currently, I found the courage to open it up yesterday evening. There were two cables plugged incorrectly: The one going to the WCPU and the one going to the RS232 connector were swapped. After swapping them back to match the labels printed where they were plugged, it started returning values :).

```
./readModbus -f4 -a1681 -s2 -t1
T water real = 59.098362&deg;C
```

**Comment by mfechner** [comment]
@plu great that it works for you now.
